services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5401:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    restart: always

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "5402:5402"
    restart: always
    command: >
      sh -c "python manage.py migrate &&
             gunicorn annotator_api.wsgi:application --bind 0.0.0.0:5402 --workers=2 --threads=2 --timeout=120 --preload"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:5402/health/"]
      interval: 10s
      timeout: 10s
      retries: 5

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "5403:80"
    depends_on:
      backend:
        condition: service_healthy
    restart: always

volumes:
  postgres_data:
