# Generated by Django 5.1.7 on 2025-03-18 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('episode_date', models.DateField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('gender', models.CharField(blank=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('weigth', models.IntegerField(blank=True, null=True)),
                ('heigth', models.IntegerField(blank=True, null=True)),
                ('medication_list', models.TextField(blank=True)),
                ('alcohol', models.CharField(blank=True)),
                ('tobaco', models.CharField(blank=True)),
                ('bariatric_surgery', models.CharField(blank=True)),
                ('depression', models.CharField(blank=True)),
                ('ansiety', models.CharField(blank=True)),
                ('pacemaker', models.CharField(blank=True)),
                ('defibrillator', models.CharField(blank=True)),
                ('arrhythmia', models.CharField(blank=True)),
                ('heart_failure', models.CharField(blank=True)),
                ('arterial_hypertension', models.CharField(blank=True)),
                ('ischemic_heart', models.CharField(blank=True)),
                ('cerebrovascular', models.CharField(blank=True)),
                ('asthma', models.CharField(blank=True)),
                ('copd', models.CharField(blank=True)),
                ('diabetes', models.CharField(blank=True)),
                ('dyslipidemia', models.CharField(blank=True)),
                ('renal_failure', models.CharField(blank=True)),
                ('thyroid_disease', models.CharField(blank=True)),
                ('dementia', models.CharField(blank=True)),
                ('cancer', models.CharField(blank=True)),
                ('ge_reflux', models.CharField(blank=True)),
                ('glaucoma', models.CharField(blank=True)),
                ('epworth_scale', models.IntegerField(blank=True, null=True)),
                ('suffocation_waking', models.CharField(blank=True)),
                ('suffocation_waking_levels', models.CharField(blank=True)),
                ('snoring', models.CharField(blank=True)),
                ('snoring_levels', models.CharField(blank=True)),
                ('apneas', models.CharField(blank=True)),
                ('apneas_levels', models.CharField(blank=True)),
                ('insomnia', models.CharField(blank=True)),
                ('insomnia_levels', models.CharField(blank=True)),
                ('complete', models.BooleanField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Episode',
                'verbose_name_plural': 'Episodes',
                'unique_together': {('patient_id', 'episode_date')},
            },
        ),
        migrations.CreateModel(
            name='Predictions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('depression', models.CharField(blank=True)),
                ('pacemaker', models.CharField(blank=True)),
                ('defibrillator', models.CharField(blank=True)),
                ('arrhythmia', models.CharField(blank=True)),
                ('heart_failure', models.CharField(blank=True)),
                ('arterial_hypertension', models.CharField(blank=True)),
                ('ischemic_heart', models.CharField(blank=True)),
                ('cerebrovascular', models.CharField(blank=True)),
                ('asthma', models.CharField(blank=True)),
                ('copd', models.CharField(blank=True)),
                ('diabetes', models.CharField(blank=True)),
                ('dyslipidemia', models.CharField(blank=True)),
                ('dementia', models.CharField(blank=True)),
                ('ge_reflux', models.CharField(blank=True)),
                ('glaucoma', models.CharField(blank=True)),
                ('suffocation_waking', models.CharField(blank=True)),
                ('suffocation_waking_levels', models.CharField(blank=True)),
                ('snoring', models.CharField(blank=True)),
                ('snoring_levels', models.CharField(blank=True)),
                ('apneas', models.CharField(blank=True)),
                ('apneas_levels', models.CharField(blank=True)),
                ('insomnia', models.CharField(blank=True)),
                ('insomnia_levels', models.CharField(blank=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='nlp.episode', verbose_name='Predictions')),
            ],
            options={
                'verbose_name': 'Prediction',
                'verbose_name_plural': 'Predictions',
            },
        ),
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expression', models.CharField(verbose_name='Expression')),
                ('color', models.CharField(verbose_name='Highlight color')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Highlight',
                'verbose_name_plural': 'Highlights',
                'unique_together': {('user', 'expression')},
            },
        ),
    ]
