# Generated by Django 5.1.7 on 2025-03-24 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlight',
            name='type',
            field=models.CharField(choices=[('Diagnostico', 'Diagnóstico'), ('Sintoma', 'Sintoma'), ('Medicamento', 'Medicamento'), ('ProcedimentoMedico', 'Procedimento Médico'), ('SinalVital', 'Sinal Vital'), ('Progresso', 'Progresso')], default='Diagnostico', verbose_name='Type of entity'),
            preserve_default=False,
        ),
    ]
