# Generated by Django 5.1.7 on 2025-03-25 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0002_highlight_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='ansiety',
            new_name='anxiety',
        ),
        migrations.RenameField(
            model_name='episode',
            old_name='heigth',
            new_name='height',
        ),
        migrations.RenameField(
            model_name='episode',
            old_name='tobaco',
            new_name='tobacco',
        ),
        migrations.RenameField(
            model_name='episode',
            old_name='weigth',
            new_name='weight',
        ),
        migrations.CreateModel(
            name='UserConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_highlight', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
