# Generated by Django 5.1.7 on 2025-03-25 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0003_rename_ansiety_episode_anxiety_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userconfig',
            options={'verbose_name': 'Configuração de utilizador', 'verbose_name_plural': 'Configurações de uilizador'},
        ),
    ]
