# Generated by Django 5.1.7 on 2025-04-09 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0005_remove_predictions_dementia_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='highlight',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='episode',
            name='user',
        ),
        migrations.AlterField(
            model_name='highlight',
            name='expression',
            field=models.CharField(unique=True, verbose_name='Expression'),
        ),
        migrations.DeleteModel(
            name='UserConfig',
        ),
        migrations.RemoveField(
            model_name='highlight',
            name='user',
        ),
    ]
